### ISSUE TITLE
this.cookies.set() cannot set cookie to chrome correctly

### ISSUE THREAD

**Issue by freestyle21** [koajs/koa#689] opened 2016-03-21 14:46 UTC
I came across a strange scene.

In the entry js file:

    app.use(function*(next) {
		this.cookies.set('test', 999999);
		return yield next;
	})

This is ok in both HTTP Response Header and Chrome Devtool Resources 's Cookies.

But...

When I put the `this.cookies.set` to Get Reponser

	app.get('/v1/test', function *(next) {
		this.cookies.set('test1', 66666);
		this.body = { code: 200, message: 'success'}
		return yield next;
	})

The HTTP Reponse Header is ok
	
	Set-Cookie: test1=66666; path=/; httponly

The Chrome Devtool Resources's Cookies display no cookie !

I have debugg this for long time, please help me ~

**Comment by PlasmaPower** [comment] 2016-03-21 15:02
The cookie is marked by default as HTTP only. If you go to network, refresh the page, click on the page load request, go to the cookies tab, you'll see that the cookie has a check mark in the HTTP column. This means that the webpage cannot access the cookie, only the server. You can set a cookie not to be httponly like this:

```js
this.cookies.set('test', 1234, { httpOnly: false });
```

More documentation can be found here: https://github.com/pillarjs/cookies

**Comment by freestyle21** [comment] 2016-03-21 15:11
@PlasmaPower Thx for reply.

I think there is no relation with `httpOnly`, `httpOnly`'s cookie can also show in the cookie panel. And I have test either `httpOnly: true` and `httpOnly: false`.

I have add a demo repo, please help me to check:

[https://github.com/freestyle21/koa-set-cookie-demo/tree/master](https://github.com/freestyle21/koa-set-cookie-demo/tree/master)

thanks.

**Comment by PlasmaPower** [comment] 2016-03-21 15:27
Those cookies are still being set with the HTTP flag in your repo

![image](https://cloud.githubusercontent.com/assets/6006498/13923517/95cdb312-ef46-11e5-82fe-5578111b4d18.png)

If you add a third argument to `this.cookies.set` which is `{ httpOnly: false }`, then it isn't marked as HTTP:

![image](https://cloud.githubusercontent.com/assets/6006498/13923622/070a80b4-ef47-11e5-9b6e-7261e11c8e24.png)

After that, typing `document.cookie` into the console will have properly set cookies.

**Comment by freestyle21** [comment] 2016-03-21 15:38
sorry that the demo repo I give may cannot display my puzzled..and I know what you said.

Simple point:

code: 

	app.use(function*(next) {
		this.cookies.set('first', 1111111, {
	    httpOnly: false
	  });
		return yield next;
	})

	app.get('/v1/test/', function *(next) {
          this.cookies.set('second', 22222, {
              httpOnly: false
          })
          this.body = {code: 200, message: 'success'}
       return yield next;
       })

chrome:

![4 pic](https://cloud.githubusercontent.com/assets/3271828/13924070/deac682c-efbd-11e5-8a32-756689fd3411.jpg)

![a](https://cloud.githubusercontent.com/assets/3271828/13924069/dea93a9e-efbd-11e5-9a56-88c0f7ff4082.jpg)

so, I don't know why the `second` is not show on chrome cookie panel.

**Comment by PlasmaPower** [comment] 2016-03-21 15:47
@freestyle21 On the first tab you screenshotted there, which showed all the requests, try clicking the cookies tab right next to headers, preview, and response. Then scroll down to the Response Cookies section. Could you take a screenshot of that?

**Comment by freestyle21** [comment] 2016-03-21 15:51
@PlasmaPower 

![5 pic](https://cloud.githubusercontent.com/assets/3271828/13924525/a85fd45a-efbf-11e5-9b32-9f3658244091.jpg)

this tab have the cookie I want ! 

but why the Resources Cookie Tab show empty??

**Comment by PlasmaPower** [comment] 2016-03-21 15:55
@freestyle21 Are you sure they are on the same domain? There's no HTTP checkbox so you're good there.

**Comment by freestyle21** [comment] 2016-03-21 16:01
@PlasmaPower 
Here is my app url:

![1](https://cloud.githubusercontent.com/assets/3271828/13924879/05b74d3a-efc1-11e5-8f2d-60e1a6986cd3.png)

![2](https://cloud.githubusercontent.com/assets/3271828/13924880/06039bb8-efc1-11e5-8f6e-102efef641ff.png)

![3](https://cloud.githubusercontent.com/assets/3271828/13924881/0612e140-efc1-11e5-84dc-3cd3c84e7116.png)

they are all in the domain `9.xiaojukeji.com`, Is there any problem?

and I don't understand your "no HTTP checkbox"...

thx.

**Comment by PlasmaPower** [comment] 2016-03-21 16:03
@freestyle21 If you type `document.cookies` in the console, does it show up there? Also, are you sure your JS isn't removing the cookies?

**Comment by PlasmaPower** [comment] 2016-03-21 16:06
@freestyle21 Also, this is certainly not a koa problem, it's either a `cookies` bug (which provides the `this.cookies` object for koa), a Chrome bug, or most likely an error with their use.

**Comment by freestyle21** [comment] 2016-03-21 16:07
`document.cookie` show only `first=1111111`, no `second=22222`. this is just my puzzled.

I have not operate the cookie in js...

so, this problem confuse me for a long time.

**Comment by PlasmaPower** [comment] 2016-03-21 16:11
@freestyle21 assuming you aren't restarting Chrome which would clear the session cookies, I can't help any more without an example demonstrating the problem.

**Comment by jonathanong** [comment] 2016-03-21 17:59
@freestyle21 hi, can you open this issue here? https://github.com/pillarjs/cookies/issues

thanks

**Closed by jonathanong** 2016-03-21 17:59 UTC

**Comment by freestyle21** [comment] 2016-03-22 02:36
@PlasmaPower @jonathanong Thx for reply. 

I find this is a bug of [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) in the end, which work well when change to jquery.

**Comment by dead-horse** [comment] 2016-03-22 03:30
@freestyle21  I think you need this https://github.com/github/fetch#sending-cookies

**Comment by freestyle21** [comment] 2016-03-22 03:47
@dead-horse oh yeah, you are right.

**Comment by luckydrq** [comment] 2016-03-23 01:54
@freestyle21 @dead-horse I think the issue aims at `receiving` cookies problem, not `sending`. If i'm wrong, correct me.

**Comment by qiuyaofan** [comment] 2018-01-11 10:39
I have the same issue.I add ctx.response.set('Access-Control-Allow-Credentials', true);
there is no error,and I can find cookie in response,but it can't add in cookie successfully.someone can help?

**Comment by nodefish** [comment] 2020-01-17 16:02
I was struggling with this and resolved it by doing the following:

- `koa-cors`: don't use a wildcard origin. I switched to the default value (which uses the origin from `req.header`), or else you get "Cannot use wildcard in Access-Control-Allow-Origin when credentials flag is true." (Firefox devtools reported this, but I was using an older Chromium that did not!).

- `koa-cors`: set the option `allowCredentials` to `true`

- Set `secure: true` on the cookie. During development this is hard to get working because chances are you have a client on http://localhost (not https -> browser quietly fails to set the cookie). I suspect there is some elaborate security logic that requires `secure: true` for CORS and/or using XHR `withCredentials`.

`ctx.cookies.set` does not work for this if you're behind a reverse proxy, because it prevents you from using secure cookies if it can't detect HTTPS. You can override that by following these instructions: https://github.com/pillarjs/cookies/issues/51#issuecomment-568182639

example:
```
const Cookies = require('cookies');
const cookies = new Cookies(ctx.req, ctx.res, { secure: true, httpOnly: true });
cookies.set('my-cookie', cookie_payload);
```

- On the client side, set `xhr.withCredentials=true` (or the `fetch` equivalent opts `{credentials: true}`).

**Comment by poode** [comment] 2021-09-26 11:18
I faced this issue, tried both chrome and firefox, and found that the issue is not related to chrome only. it exists with firefox as well

**Comment by mylastore** [comment] 2022-09-26 14:45
> ```js
> const Cookies = require('cookies');
> const cookies = new Cookies(ctx.req, ctx.res, { secure: true, httpOnly: true });
> ```

Cookies are not setting for me following the example you posted with the cookies lib.
Using Node 16.17.0, cookies 0.8.0, and Koa 2.13.4

**Comment by weiliang903** [comment] 2025-04-15 10:22
It's working for me.
```
const app = new Koa()
app.proxy = true
```

```
const cookies = new Cookies(ctx.req, ctx.res, { secure: !isLocal })
cookies.set('session', session, {
  httpOnly: true,
  maxAge: 30 * 24 * 60 * 60 * 1000, // 30 days
  sameSite: 'lax',
  secure: !isLocal,
  path: '/my-app'
})
```

**Comment by mylastore** [comment] 2025-04-17 04:11
> It's working for me.
> 
> ```
> const app = new Koa()
> app.proxy = true
> ```
> 
>  ```
> const cookies = new Cookies(ctx.req, ctx.res, { secure: !isLocal })
> cookies.set('session', session, {
>   httpOnly: true,
>   maxAge: 30 * 24 * 60 * 60 * 1000, // 30 days
>   sameSite: 'lax',
>   secure: !isLocal,
>   path: '/my-app'
> })
> ```

in my case it was my fault since my api is hosted on a separate domain, I needed to add domain: abc.com instead of sameSite: 'lax'
