### ISSUE TITLE
write ECONNABORTED

### ISSUE THREAD

**Issue by newcomein** [koajs/koa#1223] opened 2018-07-17 04:27 UTC
```
  Error: write ECONNABORTED
      at afterWriteDispatched (internal/stream_base_commons.js:75:25)
      at writeGeneric (internal/stream_base_commons.js:70:3)
      at Socket._writeGeneric (net.js:760:5)
      at Socket._write (net.js:772:8)
      at doWrite (_stream_writable.js:410:12)
      at clearBuffer (_stream_writable.js:540:7)
      at Socket.Writable.uncork (_stream_writable.js:314:7)
      at ServerResponse.end (_http_outgoing.js:733:21)
      at respond (E:\WebstormProjects\test\node_modules\koa\lib\application.js:243:7)
      at handleResponse (E:\WebstormProjects\test\node_modules\koa\lib\application.js:149:34)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

my code:
```
const Koa =require("koa")
const app =new Koa();
app.use(ctx=>ctx.body={name:"hello world"});
app.listen(4000)
```

if i run ```  autocannon -c 100 -d 5 -p 10 http://127.0.0.1:4000/ ```  will error

**Comment by hxkuc** [comment] 2018-07-18 07:11
same question
![image](https://user-images.githubusercontent.com/17510186/42865619-ce30efc8-8a9c-11e8-97ad-95d98d31645e.png)

![image](https://user-images.githubusercontent.com/17510186/42865603-c1bf31aa-8a9c-11e8-8959-b61b2691488e.png)

**Comment by theteapot** [comment] 2018-07-29 10:58
I tried what you suggested, however this is the error I received instead:
```
Error: write EPIPE
      at _errnoException (util.js:992:11)
      at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```

I tried reducing the pipelining on autocannon (down to 2) which resulted in no errors. 
Then I tried fiddling with my OS's limit on open files and it seemed that the higher I had it the more pipelined requests I could use, without getting an error. For example by setting it as high as I could (4096) it was possible for me to increase the pipelining to 3 without error.

Perhaps this means it's an OS issue? Does changing your limit on open files have any affect on the problem?

**Comment by hxkuc** [comment] 2018-07-31 05:00
if i use `http.createServer()`  this problem would not exist

**Comment by fl0w** [comment] 2018-07-31 08:05
@hxkuc do you mean with Koa (`app.callback()`) or just a plain node http server?

**Comment by fl0w** [comment] 2018-08-01 07:55
I can reproduce this on a macOS Hight Sierra (early 2018).

koa.js
```js
'use strict'
const Koa = require("koa")
const app = new Koa()
app.use(ctx => { ctx.body = { name: 'hello world' } })
app.listen(4000)
```

http
```js
'use strict'
const http = require('http')
const app = http.createServer((request, response) => {
  // Replicate Koa behaviour
  response.writeHead(200, JSON.stringify({ hello: 'hello world' }))
  response.end()
})
app.listen(4000)
```

**Comment by fl0w** [comment] 2018-08-01 08:12
this is the full stack trace from an inspect

```

  | onerror | @ | application.js:195
-- | -- | -- | --
  | emit | @ | events.js:182
  | onerror | @ | context.js:117
  | onerror | @ | application.js:147
  | listener | @ | index.js:169
  | onFinish | @ | index.js:100
  | callback | @ | index.js:55
  | onevent | @ | index.js:93
  | emit | @ | events.js:187
  | onwriteError | @ | _stream_writable.js:431
  | onwrite | @ | _stream_writable.js:456
  | _destroy | @ | destroy.js:40
  | Socket._destroy | @ | net.js:606
  | destroy | @ | destroy.js:32
  | afterWrite | @ | net.js:838
  | WRITEWRAP (async) |   |  
  | init | @ | inspector_async_hook.js:27
  | emitInitNative | @ | async_hooks.js:137
  | writevGeneric | @ | stream_base_commons.js:59
  | Socket._writeGeneric | @ | net.js:759
  | Socket._writev | @ | net.js:768
  | doWrite | @ | _stream_writable.js:408
  | clearBuffer | @ | _stream_writable.js:517
  | Writable.uncork | @ | _stream_writable.js:314
  | _flushOutput | @ | _http_outgoing.js:804
  | _flush | @ | _http_outgoing.js:779
  | assignSocket | @ | _http_server.js:179
  | resOnFinish | @ | _http_server.js:583
  | emit | @ | events.js:187
  | onFinish | @ | _http_outgoing.js:681
  | _tickCallback | @ | next_tick.js:61
  | TickObject (async) |   |  
  | init | @ | inspector_async_hook.js:27
  | emitInitNative | @ | async_hooks.js:137
  | emitInitScript | @ | async_hooks.js:336
  | TickObject | @ | next_tick.js:86
  | nextTick | @ | next_tick.js:117
  | defaultTriggerAsyncIdScope | @ | async_hooks.js:294
  | _writeRaw | @ | _http_outgoing.js:264
  | _send | @ | _http_outgoing.js:235
  | end | @ | _http_outgoing.js:727
  | respond | @ | application.js:248
  | handleResponse | @ | application.js:148
  | _tickCallback | @ | next_tick.js:68
  | Promise.then (async) |   |  
  | handleRequest | @ | application.js:150
  | handleRequest | @ | application.js:132
  | emit | @ | events.js:182
  | parserOnIncoming | @ | _http_server.js:658
  | parserOnHeadersComplete | @ | _http_common.js:109

**Comment by hxkuc** [comment] 2018-08-01 08:49
@fl0w yeah it's a serious bug

**Comment by fl0w** [comment] 2018-08-01 08:51
Actually, I retract what I previously wrote. This occurs in using a plain http server as well, Koa is just better by not swallowing the error. The following example outputs the same error:

```js
'use strict'
const http = require('http')

const app = http.createServer((request, response) => {
  response.writeHead(200, JSON.stringify({ hello: 'hello world' }))
  response.end()
})

app.on('clientError', (err, socket) => {
  throw err
})

app.listen(4000)

//  Error: write EPIPE
//      at WriteWrap.afterWrite [as oncomplete] (net.js:836:14)

// { Error: write EPIPE at WriteWrap.afterWrite [as oncomplete] (net.js:836:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
```

```sh
$ npx autocannon -c 100 -d 10 -p 10 http://127.0.0.1:4000/
```

Not sure why this is happening other than it hitting an OS limit for a sys write call.

**Comment by hxkuc** [comment] 2018-08-01 09:04
i will take this question to nodejs repositories

**Comment by fl0w** [comment] 2018-08-01 09:13
Increasing maxfiles on macOS from 256 to 262144 didn't reduce N errors.

**Comment by fl0w** [comment] 2018-08-01 09:25
I wouldn't, this could easily be an autocannon issue. I can't reproduce the error using ab.

**Comment by hxkuc** [comment] 2018-08-01 09:29
you mean it's a bug of autocannon?

**Comment by fl0w** [comment] 2018-08-01 09:30
No, I'm saying it wouldn't automatically assume it's a node lib bug.

**Comment by hxkuc** [comment] 2018-08-01 09:34
Thanks a lot. Let me try it again

**Comment by fl0w** [comment] 2018-08-04 09:40
I'm going to close this as according to my investigation this isn't a Koa issue. Please feel free to re-open if your findings shows otherwise.

**Closed by fl0w** 2018-08-04 09:40 UTC
Labels: invalid
