### ISSUE TITLE
koa 3.0 roadmap

### ISSUE THREAD

**Issue by dead-horse** [koajs/koa#1114] opened 2017-12-24 06:59 UTC
There are lots of PRs are blocked due to breaking change, and maybe it's time to make a plan for koa 3.0 now, if anyone has other suggestion, please post in this issue. :)

- https://github.com/koajs/koa/issues/1044
- https://github.com/koajs/koa/issues/1008
- https://github.com/koajs/koa/issues/998
- https://github.com/koajs/koa/issues/904
- https://github.com/koajs/koa/pull/1011

**Comment by fl0w** [comment] 2017-12-24 09:19
Is it to early to create a v3 branch? I have some spare time coming up and wouldn’t mind doing some work.

**Comment by dead-horse** [comment] 2017-12-24 12:52
All these pending PRs are not so emergency to me, so if anyone has any thoughts or some feature / refactor required, post in the issue to help us decide when to start create v3 branch. :)

**Comment by fl0w** [comment] 2017-12-26 19:24
How about officially dropping support for < node.js 8?

**Comment by iyuq** [comment] 2017-12-27 03:04
`koa-compose` 可以用 `async/await` 重写下

**Comment by iyuq** [comment] 2017-12-27 03:13
totally rewrite using `Typescript`

**Comment by fl0w** [comment] 2017-12-27 09:33
I'm personally against introducing TypeScript, adding external typings should be easy enough for those in need.

**Comment by marswong** [comment] 2018-01-08 14:30
> How about officially dropping support for < node.js 8?

@fl0w IMO, engines support should always follow the [Node.js release schedule](https://github.com/nodejs/Release#release-schedule) :)

**Comment by marswong** [comment] 2018-01-08 14:49
> totally rewrite using TypeScript

like what @fl0w said above, just one more thing:
`koa` is quite vary from `egg`、`express` and any other **framework**. It's just a pure http request middleware close to `Node.js` as you can see. So we can just feel free to write in pure JavaScript, follow the traditional convention and trust `Node.js` :)

**Comment by jonathanong** [comment] 2018-01-31 05:24
if you have any breaking changes you'd like to introduce, please state them now :)

**Comment by fl0w** [comment] 2018-02-12 12:01
Let's announce EOL for Koa v1.

**Comment by zhangxiang958** [comment] 2018-03-29 11:55
How about support HTTP/2 ? https://nodejs.org/api/http2.html

**Comment by hiroqn** [comment] 2018-05-09 14:19
How about publish `koa` and official middleware module under `@koajs/` ?

**Comment by likegun** [comment] 2018-05-17 01:17
I think [#1044](https://github.com/koajs/koa/issues/1044) is already solved by this merged [commit](https://github.com/koajs/koa/commit/3c23aa5b74d19352e0a78d135df5ed6979d4e242)

**Comment by tiendq** [comment] 2018-07-18 13:48
I think `context.res` and `context.req` are not good names and they make people confused with `context.response` and `context.request`. Is it better if we can name them behind `NodeJS` names, so `context.res` becomes `context.serverResponse` and `context.req` becomes `context.incomingRequest`?

**Comment by ng-** [comment] 2018-08-06 21:56
@tiendq I completely agree!  I keep mixing up `req/request` and `res/response`.  I vote for something like
```
{
req:<koa request>,
res<koa response>:,
raw:{
   req:<node request>,
   res:<node response>,
}}
```

**Comment by damianobarbati** [comment] 2018-10-07 09:31
How to access the http2 stream on ctx object to push assets to client using koa? It this supported right now?

**Comment by mike-tobia** [comment] 2018-10-08 00:16
I second @damianobarbati , would be great to get an implementation snippet that displays the compatibility and its usage. For example, would the stream be accessible through `ctx.res.stream`?

I've been seeing a bit of chatter on HTTP/2 support for Koa - I agree that we don't need to define config just to "enable" out of the box. What we do need however, is an interface to utilize HTTP/2, let's say if the request type is HTTP/2, maybe context could be formed at this stage.

I believe that the moment the Koa community takes a stance on HTTP/2, this would promote its usage for the next generation of servers built using Koa. To me, this is a great step forward.

What I envision, as a mode of compatibility and usage, is to add `ctx.stream` if the request is in an HTTP/2 context. As a start, we could yield the benefits of pushing from the stream and get a grip on how to manage push streams without ending the connection prematurely.

**Comment by Tajnymag** [comment] 2018-10-10 11:03
> How about publish `koa` and official middleware module under `@koajs/` ?

Why not simply @koa/?

**Comment by Hiswe** [comment] 2018-10-16 03:28
Here is my little suggestions

- #1044 because more and more people are using next/nuxt applications (or maybe not by I am…)
- and as said by @Tajnymag a `@koa` namespace can be useful:
  - [@koa/cors](https://www.npmjs.com/package/@koa/cors) is already namespaced
  - it will be clearer what are the official middleware
  - for new adopter, it makes more easy what to safely start with.
     IMO “official” guaranties that it plays nicely with the framework and will be maintained over time
- `optional` some typescript types if needed as this language is getting more and more traction

**Comment by maticrivo** [comment] 2018-10-17 11:53
+1 on #1044

**Comment by midnightcoder-pro** [comment] 2019-01-19 17:46
Please do normal error handling. The ability to set content type

**Comment by catsalive** [comment] 2019-04-05 20:42
+1 on #998

**Comment by dolsup** [comment] 2019-04-26 06:30
I suggest #1326

**Comment by Hanggi** [comment] 2019-05-23 02:31
Is there any timeline or schedule for 3.0?

**Comment by libook** [comment] 2019-09-17 02:31
Need some help?

**Comment by tinovyatkin** [comment] 2019-10-15 12:33
I think removing `next` parameter from middleware and just awaiting all middleware can be most useful breaking change in 3.0.
Debugging something like bellow is a nightmare:
```js
app.use(async (ctx, next) => {
 // ... do something
 await next();
// ... do some more staff
})
app.use(async (ctx, next) => {
 // ... do something
 await next();
// ... do some more staff
})
```
while removing `next` will make composition simple and `koa-compose` will not be needed:
```js
// koa-compose will not be needed, just do this:
  async handleRequest(ctx) {
    const res = ctx.res;
    res.statusCode = 404;
   try {
     for (const handler of this.middleware) {
        await handler(ctx);
     }
   } catch (err) {
     ctx.onerror(err);
  }
}

```

if something need to be guaranteed last handler then it can use [events](#1395) or better composition and `.state`

**Comment by octet-stream** [comment] 2019-10-15 12:46
@tinovyatkin What if you need to do something after the `next()` call?
For example, I'm using this scenario in multipart middleware:
```js
import {parse} from "then-busboy"
import {unlink} from "promise-fs"

const unlinkFile = ({path}) => unlink(path)

const methods = ["post", "put"]

async function multipart(ctx, next) {
  if (!methods.includes(ctx.method.toLowerCase())) {
    return next()
  }

  if (!ctx.is("multipart/form-data")) {
    return next()
  }

  const body = await parse(ctx.req)

  ctx.request.body = body

  await next()

  // Cleanup files
  return Promise.all(Array.from(body.files.values()).map(unlinkFile))
    .catch(err => err.code !== "ENOENT" && Promise.reject(err))
}

export default multipart
```

How can I do so without `next()` as simple as this?

**Comment by tinovyatkin** [comment] 2019-10-15 14:05
@octet-stream you mean if you ship your middleware as a module? With proposed #1395 you may do it easily:

```js
app.use(async ctx => {
  if (methods.includes(ctx.method.toLowerCase() && ctx.is("multipart/form-data"))
    ctx.request.body = await parse(ctx.req)

 this.once('responded', async () => {
     // Cleanup files
   if(ctx.request.body.files) {
    try {
      await Promise.all(Array.from(body.files.values()).map(unlinkFile))
    } 
   catch (err) {
       if(err.code !== "ENOENT" ) throw err;
   }
  finally {
   delete ctx.requests.body.files;
  }
   }
 })
})
```

In your current implementation you actually deleting files from disk _before_ response is sent to the network and if response stream is destroyed, so, if these files have opened read stream you can get in trouble.

**Comment by fl0w** [comment] 2019-10-15 14:22
@tinovyatkin I don't see it.

We'd have to (again) ostracise the entire ecosystem. You're essentially removing an abstraction that is well understood for no real benefit. Personally I haven't had issues debugging current middleware signature and usage, and there's also no evidence that this is a general issue either (just from experience by idling in Koa issues).

Just be using your own example against you, even glanceability goes out the door.

It feels like a change for the sake of change? But maybe I'm missing something?

**Comment by tinovyatkin** [comment] 2019-10-15 14:25
@fl0w see [my response and example for @octet-stream](https://github.com/koajs/koa/issues/1114#issuecomment-542229407) - developers tends to think that after awaiting `next` it's safe to cleanup resource while, in fact, the response is not even sent to the network at that point. Removing `next` will force to think the whole serving lifecycle right.

**Comment by octet-stream** [comment] 2019-10-15 14:28
> In your current implementation you actually deleting files from disk before response is sent to the network and response stream is destroyed, so, if these files have opened read stream you can get in trouble

Sure, in actual code I would decide to cleanup files out of a request processing, because of something here will crash – the request will be also crash. It was just an example of a case where you need to do something after the next middleware is called, or maybe before respond. And the question was how to do so if your proposal will be added? Guess I need to clarify my thoughts better :)

**Comment by tinovyatkin** [comment] 2019-10-15 14:30
@fl0w what will happen if in [above example by @octet-stream](https://github.com/koajs/koa/issues/1114#issuecomment-542193509) he will forgot to await the next and just call `next()`? It will very hard to find race condition.

**Comment by tinovyatkin** [comment] 2019-10-15 14:35
@fl0w if the `next` is well understood, following are some easy questions:
1. If I will not call `next` in my middleware is it guaranteed than no middleware will be run after my processing?

2. If I call, but not await `next` - will I start parallel request processing with this and whole middleware stack will wait for my middleware to finish anyway?

**Comment by tinovyatkin** [comment] 2019-10-15 14:40
@iyobo the example @octet-stream posted most probably will result in race condition if a next middleware will open a read stream on files. Making developers understand that is exactly the point of removing `next`

**Comment by fl0w** [comment] 2019-10-15 21:41
@tinovyatkin there was a discussion about missing `await next()` but I think it ended in agreement that it is impossible to protect users from common JS mistakes.

You're mixing streams, promises and events to make a case, and I can understand it gets confusing, but that's not the fault of Koa tbh. Personally, I find it quite simple. When the topmost promise resolves Koa tries to respond.

> developers tends to think that after awaiting next it's safe to cleanup resource while, in fact, the response is not even sent to the network at that point

That might or might not be true, I'll argue it's not as big of a problem as you're asserting. Koa 2 has been out for quite some time. I'd say I've been pretty active answering general usage questions, both in issues here and on slack and I don't see the evidence to support your case (others might disagree). Had this been a major issue it would have popped up.

> If I will not call next in my middleware is it guaranteed than no middleware will be run after my processing?

Unless you do something hacky, sure. Why would it? It's how promises and regular functions work. If you don't call it, it will not be called (maybe I misunderstood your question here?)

> If I call, but not await next - will I start parallel request processing with this and whole middleware stack will wait for my middleware to finish anyway?

If you call a promise but don't return, chain or await it'll run out of context (which isn't equivalent to parallel btw). Notice that the explanation has nothing to with Koa but rather the atomics of how a promise works.

In your response to @octet-stream you propose using events (I haven't tried your PR nor your example). To me this reads like you just introduced a bug because you're trying to respond in the event handler which is out of context. Koa doesn't "care" if these events exists or not.

I don't see the benefits. The current design is simple and not a unique concept (e.g. Go http in standard library provides the same pattern).

I am strongly -1 on removing next.

**Comment by nbcarey** [comment] 2019-10-25 23:43
@tinovyatkin said (and I quote):

> I think removing `next` parameter from middleware and just awaiting all middleware can be most useful breaking change in 3.0.
> . . . 
> while removing `next` will make composition simple and `koa-compose` will not be needed:
> 
> ```js
> // koa-compose will not be needed, just do this:
>   async handleRequest(ctx) {
>     const res = ctx.res;
>     res.statusCode = 404;
>    try {
>      for (const handler of this.middleware) {
>         await handler(ctx);
>      }
>     respond(ctx);
>    } catch (err) {
>      ctx.onerror(err);
>   } finally {
>     // any finalisation logic here
>   }
> }
> ```

The problem is that by removing `next()`, you eliminate the highly useful nesting aspects of Koa
s middleware:
* Requests traverse the middleware chain on their way down **and** on the way back up.
* Any middleware can short-circuit the remainder of the pipeline.
* Each middleware can maintain state between its `before` and `after` phases. This, in particular, makes doing things like measuring elapsed time and logging `begin` and `end` events clean, elegant, and  _really_ easy.

Without this, common tasks, like, say, measuring elapsed time and logging a `begin` and `end` event would require (1) two separate pieces of middleware, (2) adding data to the request context, and (3) possibly never logging the `end` event because an exception was thrown.

In Koa, each piece of middleware _decorates_ and wraps the next rather than simple concatenation like you see with most middleware implementations.

It would be a shame to lose that.

**Comment by pke** [comment] 2019-11-15 19:52
I agree with @nbcarey after my recent journey to `polka`. I never really understood how the "middleware" there is really only an "upstream-ware". It does not sit in the middle of the execution process. At least not in a useful way (for me) like `redux` and `koa` use it.

In koa I can easily have one place were I finally format the response according to the request `Accept` header or add a `Location` header based on certain context information.

This middleware concept of up- and downstream handling I find too useful to be broken.

I have to say though the performance difference between polka and koa is visible.
Anyone knows where the most time is spent in koa? Maybe this could also be tackled in a next major release.

**Comment by blacksonic** [comment] 2020-02-18 10:58
Is there a plan to release v3?

**Comment by hufeishuo** [comment] 2020-05-17 07:20
> How about publish `koa` and official middleware module under `@koajs/` ?

need more resource/people  to maintain

**Comment by Ajaxy** [comment] 2020-05-22 21:34
Why is this repo so calm? What do people use now instead of it? Is Express still the "default option" with all its callback hell?

**Comment by pke** [comment] 2020-05-22 21:45
I'd guess they are using more and more serverless or old express servers that work.

**Comment by iyobo** [comment] 2020-05-22 22:41
The pros of serverless hardly ever outweigh the cons. There is still that annoying warmup and warmth maintenance. My thing is, If you have to do that, just have a server running. Those are easy enough to create and run in node land.

But I digress...

The thing about koa is that it is so modular that the lack of repo activity is actually one of its features, not a sign of its decay. There really isn't anything major that can be added to Koa that cannot be created as a separate plugin so as not to overload the middleware pipeline with what is not needed per implementation.

**Comment by pke** [comment] 2020-05-23 00:21
I agree with your thoughts about serverless, although I use it sometimes to quickly try out some ideas.

What I would like to see here for koa is more speed improvement but a TS seems also a nice goal.

**Comment by kubejm** [comment] 2020-06-11 02:44
I've been chipping away at converting this project to TypeScript to get more hands on experience with TypeScript and to learn more about the inner workings of this project.  I have it nearly converted and ported all the tests to Jest as well.

Along the way I made some slight changes to the implementation to accommodate typing and simplify some logic.  I've annotated some of my questions/thoughts along the way.  However, I have a little bit of work and clean up left.

https://github.com/kubejm/koa-ts

**Comment by aksdevac** [comment] 2020-06-23 15:35
@Ajaxy 
> Why is this repo so calm? What do people use now instead of it? Is Express still the "default option" with all its callback hell?

There are other options for express like https://www.fastify.io/ OR https://hapi.dev/

**Comment by lagden** [comment] 2020-06-27 04:21
I think superset is bad!
Many projects move to TypeScript and appears a lot of "type issues".

But I agree make a TS version to run on [Deno](https://deno.land/) in another repository.

**Comment by crazybber** [comment] 2020-06-30 01:31
> I think superset is bad!
> Many projects move to TypeScript and appears a lot of "type issues".
> 
> But I agree make a TS version to run on [Deno](https://deno.land/) in another repository.

type issue is one of  basic and necessary cost to move to TS,  but i think benefit is more than cost

**Comment by codingnan** [comment] 2020-07-04 11:03
how about base on  uWebSocket.js. it's so fast.

**Comment by LeonnardoVerol** [comment] 2020-07-07 09:58
Definitely #1326

**Comment by X-neuron** [comment] 2020-10-22 14:40
How about support HTTP/3  https://nodejs.org/dist/latest-v15.x/docs/api/quic.html

**Comment by draconteus** [comment] 2021-03-05 14:35
> I'm personally against introducing TypeScript, adding external typings should be easy enough for those in need.

Downside of this that external type declarations can be easily broken or lagging the koa releases.
E.g.: current version of `@types/koa` at 2.13.1 has wrong typing for context.response, no version of 2.12.x was ever released...

**Comment by iyobo** [comment] 2021-03-05 15:12
What drew me to koa back then was that it was using generators from the core while others were still using nasty callbacks.  Koa was technologically ahead. Now async/await is everywhere, but I stuck with koa because I had already built quite a few frameworks on it... Even though Koa isn't the most economically viable space to invest in right now as far as popularity.

Now I see koa kinda lagging behind in a lot of things. And I believe it's partly because TJ and other OGs have moved on to other things. But that's good for them.

I will say that if koa 3 does not come inbuilt with typescript, that will be the final nail in the coffin for koa and will keep it in the land of hobby/amateur/not-professional-use. Types are a thing now and are invaluable when working with huge teams, whether anyone likes it out not.

**Comment by iyobo** [comment] 2021-03-05 15:19
> I think superset is bad!
> Many projects move to TypeScript and appears a lot of "type issues".
> 
> But I agree make a TS version to run on [Deno](https://deno.land/) in another repository.

Type issues can be solved by simply understanding typescript. You can make typescript as strict or as lax as you want. At the end of the day, there is value in even the most lax typescript implementation.

A TS version can also serve normal JS users as well as TS users, with the TS users getting a better dev experience right out the back.

Also not a fan of external typings as they go out of sync.

**Comment by lagden** [comment] 2021-03-05 17:45
@iyobo 

It doesn't make sense to me!
Won't keep 2 versions.
Will be the another project with same concept.

Deno runs native TS (as another language).
It's much better than "superset project"!

I keep my opinion.

**Comment by nickmccurdy** [comment] 2021-03-06 00:00
If we migrate the project to TS, that single version can be used in both TS and JS. I'd personally recommend that based on the future needs of Koa and the community moving toward strong TS support. I can probably help with migration, but I don't think I'd have time to do all of it on my own.

**Comment by kubejm** [comment] 2021-03-06 04:16
@nickmccurdy I'd be willing to help if there is desire to migrate.  I took at stab at rewriting koa in TS the middle of last year and opened an issue (https://github.com/koajs/koa/issues/1475), but it did not seem pressing to make the transition at the time and was closed.  However, if there is renewed interest, then https://github.com/kubejm/koa-ts might be a reasonable jumping off point.  It's likely a little stale, because I have not kept up with changes since the issue was closed in June of 2020.

**Comment by jimmywarting** [comment] 2021-11-05 11:13
I don't think there is a reason to migrate to TS, jsdoc works just as well with typing support.
My personal experiences working with TypeScript and ESM in some projects is a total nightmare with the extensions.

There is many things Typescript gets wrong, it have no understanding of `Symbol.toPrimitive` and classes that has things like `toString()` so most often it complains on things like `fetch(new URL(...))` which is totally valid to do, but something TS complains about. I don't think typescript fits in a loosed typed language. It's like trying to put a square into a circle.

It's just lagging behind in many areas so it will always stand in the shadow of javascript, when something new comes out then typescript will take for ages to adapt to new changes. 

I have written a vanilla javascript project for both Deno and NodeJS with jsdoc and love and behold you get typing/ide support from both worlds using npm and http-import using the Deno plugin for vscode and without any d.ts or ts files

Typescript just adds complexity to a project, i have worked with it JS in 12 years, two of those years i have activlly used TS back and forth, i don't think it adds any real marginal productivity, you will spend lots of time just making some simple JS function compliant to the TS rules. it also adds lots of wasteful compile time and unnecessary dependencies. Deno stop using Typescript for a couple of reasons which i can only agree upon 

Its very much possible to have typing and esm code without using Typescript syntax and having it work for both Deno and Node

**Comment by alanpurple** [comment] 2021-12-20 00:53
@jimmywarting 
what on earth does the Browser issue come to server-framework matter?

**Comment by jimmywarting** [comment] 2021-12-20 01:03
@alanpurple my point is that TypeScript will never be a first class language in browser or nodejs - https://stackoverflow.com/a/8947021/1008999 
it's just one of many languages that needs to compile to javascript.
The idea of having a multiple vms platform support for many languages is not desirable

I just created [this page](https://jimmywarting.github.io/you-might-not-need-typescript) to prove my point that you don't actually need typescript

**Comment by draconteus** [comment] 2021-12-20 09:39
> I just created [this page](https://jimmywarting.github.io/you-might-not-need-typescript) to prove my point that you don't actually need typescript

Although there are some valid points in your writing, most of them are just straight bad.
The community needs strong Typescript support, because even if you can do this: `1 + true` is vanilla JS, doesn't mean you wanted to do so. Typescript is exactly made for to avoid the bad practices can be done in vanilla JS.

**Comment by iyobo** [comment] 2021-12-20 15:33
> There is a beautie in a dynamic loosed type system too and there is nothing wrong with it that needs to be fixed, there have been one time where i actually wanted to do `+= boolean` instead of `+= boolean ? 1 : 0`
> 
> js have very many toPrimitive (or rather webidl conversion) hacks in a lot of the builtin web api's that typescript don't understand, one very common such thing is casting anything to string. anywhere where a web api expect a byteString, number or a boolean there is a webidl converter that is suppose to cast whatever argument you gave it into the correct type.
> 
> i don't think the community needs stronger typescript support, i think it needs optional static typing instead builtin instead.
> 
> and if you feel so strongly about types (and possible coming from a other typed language) why not just stick to it and compile to WebAssembly instead?

You do realize Typescript allows for "Optional static typing" right?
Would it not then be best to support Typescript so those who want static typing can use it and the lovers of aorphous blobs can carry on with their implicit `any`s?

BTW: If anyone wants to a tool to define koa endpoints+validation using Typescript annotations and classes, check out https://www.npmjs.com/package/amala

**Comment by jimmywarting** [comment] 2021-12-20 19:24
> You do realize Typescript allows for "Optional static typing" right?

[optional static typing](optional static typing) proposal !== TypeScript

**Comment by iyobo** [comment] 2021-12-20 19:39
> > You do realize Typescript allows for "Optional static typing" right?
> 
> [optional static typing](https://github.com/sirisian/ecmascript-types) proposal !== TypeScript

The decision we make about this will determine how attractive the Koa ecosystem will be to end-users.
Particularly enterprise end-users, who tend to bring **jobs** and **financially support** to ecosystems they rely on. 

Typescript will not only allow for what you are proposing, but also open the gates to more serious engagement in this ecosystem.

We have to mature Koa past these personal hack/blob preferences.

**Comment by libook** [comment] 2021-12-23 08:12
For me, Typescript is just a tool for ECMAScript. Well, there is not only one tool for such purpose.

Flexibility can be exchanged for team-work efficiency. That is what employers need.
So of course, there should be declaration files for koa; for teams who use Typescript. (There already are.)

But it doesn't mean that koa should be writen with Typescript.
In one hand, koa project don't need to use flexibility to exchange team-work efficiency.
In other hand, there is not enough benefit for the developing work of this project.
In fact, users(who use koa for developing) need not to care about the detial of koa. High quality API and document are enough.
Koa is good, people konw. They don't need Typescript to be the reason.

If koa switch to Typescirpt, there is also a voice from people who don't want to include Typescript compiler in their projects.

Typescript is not a silver bullet. I don't want to argue much about it. I just share my opinion as a heavy user of koa. And wish we don't spend too much time on this.

**Comment by fgarcia** [comment] 2021-12-23 12:22
> If koa switch to Typescirpt, there would also be a voice from people who don't want to include Typescript compiler in their projects.

Actually, it has never been necessary a Typescript compiler to consume Typescript packages. Typescript projects export plain JS along type definition.

Moving the source code to Typescript should only be made if it brings value to the maintainers working on the code, and I do believe Typescript lowers the difficulty for beginners to make code contributions. Also to refactor and clean up code.

Given the low API surface, I would be surprised if a plain Koa user/consumer could gain any benefit beyond what the @types/koa already gives

**Comment by rayfoss** [comment] 2022-06-17 05:58
> I'm personally against introducing TypeScript, adding external typings should be easy enough for those in need.

Middle ground that will probably appease the TypeScript and the anti-bundler crowd...
https://github.com/typicode/lowdb

They build their extremely popular library on pure ES Modules... no bundlers needed... Node LTS as of 16, aka the current LTS release as of two years ago has stable support for ES Modules.

Personally I just want the official typed examples... seriously what's the type of the response object! ... I'm sure I'll figure it out eventually, I may have to read the DT source code. I'm talking about docs like the one pictured below... absolutely no one in 2022 should ever type the word `require(`

![Screenshot 2022-06-17 00 57 23](https://user-images.githubusercontent.com/876076/174234675-d7a5d5be-44c9-47bb-b8f7-1af659f588d8.png)

**Comment by rotkiw** [comment] 2023-07-30 20:44
Is this a dead horse? 'cos it looks like a dead horse. :skull: :horse:

**Comment by imaksp** [comment] 2023-07-31 05:59
> Is this a dead horse? 'cos it looks like a dead horse. 💀 

It looks like this is not well maintained, for new TS based projects users can consider libs like [tinyhttp](https://github.com/tinyhttp/tinyhttp). but it might be slower than koa, users can also consider hyper express if req/sec is very important.
See this for comparison:
https://web-frameworks-benchmark.netlify.app/result?f=tinyhttp,express,hyper-express,koa

**Comment by talentlessguy** [comment] 2023-11-07 23:52
> > Is this a dead horse? 'cos it looks like a dead horse. 💀
> 
> It looks like this is not well maintained, for new TS based projects users can consider libs like [tinyhttp](https://github.com/tinyhttp/tinyhttp). but it might be slower than koa, users can also consider hyper express if req/sec is very important. See this for comparison: https://web-frameworks-benchmark.netlify.app/result?f=tinyhttp,express,hyper-express,koa

huge thanks for spreading the word about the project! Agree on the performance side, but the benefit is better compatibility with middleware / smoother transition from express

**Comment by jonathanong** [comment] 2024-08-29 00:31
moving the tracker to here: https://github.com/koajs/koa/issues/new?assignees=&labels=enhancement&projects=&template=---feature-request.md&title=%5Bfeat%5D+DESCRIPTIVE+TITLE

**Closed by jonathanong** 2024-08-29 00:31 UTC
