### ISSUE TITLE
Koa with http2 cannot get request

### ISSUE THREAD

**Issue by Rukeith** [koajs/koa#1147] opened 2018-02-15 09:11 UTC
I use http2 with koa.

```
http2.createServer(app.callback()).listen(3000, () => {
  console.info('===========================================');
  console.info('===== Server is running at port: 3000 =====');
  console.info('===========================================');
});
```

But when I  use browser to hit `127.0.0.1:3000`. Server didn't get any request at console.
I am not sure it is koa or middleware's issue.
Here is my sample https://github.com/Rukeith/blog-server/tree/http2-demo

**Comment by fl0w** [comment] 2018-02-15 09:58
Try

```js
const cert = {
  cert: fs.readFileSync(path.join(__dirname, 'path/to/cert.pem')),
  key: fs.readFileSync(path.join(__dirname, 'path/to/key.pem'))
}

const server = http2.createSecureServer(cert, app.callback())
```

https://nodejs.org/api/http2.html#http2_server_side_example

**Comment by mjbradford89** [comment] 2018-02-21 20:22
Having the same issue.

@fl0w  using `createSecureServer` does not fix it unfortunately :cry:

**Comment by fl0w** [comment] 2018-02-22 06:22
I cannot reproduce your error, the following is working as intended:

```js
'use strict'
const fs = require('fs')
const path = require('path')
const http = require('http2')
const Koa = require('koa')
const app = new Koa()
const cert = {
  cert: fs.readFileSync(path.join(__dirname, './localhost-cert.pem')),
  key: fs.readFileSync(path.join(__dirname, './localhost-privkey.pem'))
}

app.use(({ body }) => body = 'hello world')

const server = http.createSecureServer(cert, app.callback())
  .listen(3000, () => console.log('goto https://localhost:3000'))
```

There's probably something else in your code or on your computer that blocks connections. Unless you provide a minimal reproducible example I'm afraid little help can be given.

**Comment by fl0w** [comment] 2018-03-05 09:42
I am going to close this for now.

Feel free to re-open if you still assert Koa to be the issue showcased with a minimal reproducible example.

**Closed by fl0w** 2018-03-05 09:42 UTC
Labels: question

**Comment by nhhockeyplayer** [comment] 2018-12-30 16:48
this is terrible because its happening now with my code

**Comment by marioavs** [comment] 2019-02-11 03:43
There are no browsers known that support [unencrypted HTTP/2](https://http2.github.io/faq/#does-http2-require-encryption)
