### ISSUE TITLE
hook on compose

### ISSUE THREAD

**Issue by jeromew** [koajs/koa#196] opened 2014-01-20 10:56 UTC
currently in application.js we have

    var compose = require('koa-compose');

and then in app.callback

    var gen = compose(mw);

I am working on an auditing middleware that tries to measure the impact of each middleware in a koa application in order to help people understand the 
1/ the middleware path taken by the requests inside their application
2/ have stats on each middleware impact

at this point i am hitting a wall because I realize that big applications are going to be built by composing composed application (cf koa-mount for instance).

my question is : would you accept a PR that would do

    function Application() {
        ...
        this.compose = compose

and

    var gen = this.compose(mw);

this way a koa app could expose its composer to other components and they could share a custom composer.

I could try and package what I already have on this audit thing if you want to see it to better understand what I am talking about.

**Comment by jonathanong** [comment] 2016-03-04 03:47
shoot. going to close this as a dupe of https://github.com/koajs/koa/issues/219

@jeromew @hallas please provide your opinion of https://github.com/koajs/koa/issues/219#issuecomment-192081855

**Closed by jonathanong** 2016-03-04 03:47 UTC
Labels: enhancement
