### ISSUE TITLE
Don't use jest --forceExit

### ISSUE THREAD

**Issue by nickmccurdy** [koajs/koa#1064] opened 2017-09-18 14:52 UTC
This is an antipattern since it can make running the test watcher less performant and the flag is meant to be a temporary solution. The best way to fix this is by passing `app.callback()` to supertest instead of `app.listen()`. The former has a server automatically created and closed by supertest, while the latter creates an unclosed server.

**Comment by likegun** [comment] 2017-09-19 01:28
Jest will invoke `.createServer()` and `server.listen(0)` if you pass `app.callback()` to the constructor, there is no difference whether you pass `app.callback()` or `app.listen()`.

**Comment by nickmccurdy** [comment] 2017-09-19 02:38
There is no difference in how the server is requested, but the server is automatically created *and closed* when you use `app.callback()` . `app.listen()` does not automatically close the server, it stays open. We could set up after each statements in every test suite to manually close the servers, but I find it easier to just use `app.callback()`. See https://github.com/koajs/koala/pull/55/commits/31b6f42609f6c0ec20713a84a6f2ea626e9a49ae.

**Comment by likegun** [comment] 2017-09-19 03:31
You are right, supertest only close server that is self created.
[supertest close server only if server(this._server) is set](https://github.com/visionmedia/supertest/blob/199506d8dbfe0bb1434fc07c38cdcd1ab4c7c926/lib/test.js#L126)
[supertest only set this._server when it's self created server](https://github.com/visionmedia/supertest/blob/199506d8dbfe0bb1434fc07c38cdcd1ab4c7c926/lib/test.js#L59))

**Comment by fl0w** [comment] 2017-09-19 07:26
> Jest will invoke .createServer() and server.listen(0) if you pass app.callback() to the constructor.

What constructor? The test?

**Comment by likegun** [comment] 2017-09-19 08:06
@fl0w Oh sorry, the supertest function not constructor. The problem is that if we use supertest this way`request(app.listen())`, supertest will not close the koa server automatically when `request.end()` is invoked.See this [issue](https://github.com/koajs/koa/issues/1061#issuecomment-330421733)

**Comment by likegun** [comment] 2017-09-26 06:35
@nickmccurdy close it?

**Comment by nickmccurdy** [comment] 2017-09-26 16:14
Thanks! Looks like we forgot to remove the flag though, see #1071.

**Closed** 2017-09-27 02:58 UTC
