### ISSUE TITLE
Error handling send JSON

### ISSUE THREAD

**Issue by adrianwix** [koajs/koa#1347] opened 2019-06-25 08:06 UTC
Hi I am trying to send an error with ctx.throw() or be simply assigning it to ctx.body but Body in the response is always empty. When trying to send it passing a third property to ctx.throw() like [here](https://github.com/koajs/koa/blob/master/docs/api/context.md#ctxthrowstatus-msg-properties) it doesn't show in the response body

I am using Mocha, Chai, Chai-http for testing. res.body is always empty. res.error has the error message but not the object.
```
test.only('Missing required fields', function (done) {
	chai
		.request(server)
		.post('/api/issues/test')
		.send({
			issue_title: 'Title'
		})
		.end((err, res) => {
			assert.isNull(err);
			console.log(res.body);
			assert.isNotFalse(res.error);
			assert.equal(res.status, 400);
			assert.equal(res.error.text, 'Project validation failed');
			done();
		});
});
```
I tried emitting the error like this,
```
const projectSave = await project
	.save()
	.catch(err => {
                // ctx.body = { hello: 'world' } this cause and error
		ctx.throw(400, 'Project validation failed', { hola: 'mundo', hello: 'world' });
	});
```
Also if I assign an object to ctx.body just before ctx.throw I get the following error `"Unexpected token P in JSON at position 0". 
I thought to do like in express ´return res.json(err)´ but in this case assigning the response to ctx.body and returning. Sadly the execution doesn't stop.

How can I send a json or javascript object in the response to use in the UI?

**Comment by fl0w** [comment] 2019-07-01 07:53
Unfortunately, I can't extract what the problem is from your description. Please a fully reproducible example and I can take a look at it.

Generally, sending POJOs as JSON is as simple as assigning the object to `ctx.body`, e.g.

```js
app.use(async ctx => {
  try {
    ctx.body = await Project.forge().save() // bookshelf example
  } catch (err) {
    ctx.body = { error: true, message: 'oopsie' }
  }
})
```

**Comment by adrianwix** [comment] 2019-07-02 16:57
@fl0w, In that case, how do I stop the execution? There is code underneath

**Comment by fl0w** [comment] 2019-07-08 11:28
If you don't call next, execution will not continue down the middleware chain. Maybe I don't understand your question?

**Comment by adrianwix** [comment] 2019-07-09 22:12
If you wish to replicate. The [Project](https://github.com/adrianwix/portfolio/blob/master/routes/api/issueTrackerApi.js) is there, it include a folder .vscode with the debugging setup. To run use `yarn start` and in vscode go to debug select `Mocha Current File` and run the test [here](https://github.com/adrianwix/portfolio/blob/master/routes/api/test/issueTrackerApi.spec.js)

In the `issueTrackerApi.js` take a look at the `post` route. Notice the await newProject.save().catch(). If I do it like what you tell me `project().save().catch(err => ctx.body = project.issues[0]);`. I get the following error `TypeError: Cannot read property 'issues' of undefined at module.exports.router.get.post (C:\Users\adrian\Code\portfolio-next-koa\routes\api\issueTrackerApi.js:94:23)` because the execution of the code does not stop and reach the line of code that says. 

Also if I do the following
```
const projectSave = await project
	.save()
	.catch(err => {
		ctx.body = { err: err };
		ctx.throw(400, 'Project validation failed');
	});
```
I get the following error `"Unexpected token P in JSON at position 0"`

How can I throw an error and return a custom error obj like for example `error = { name: 'required', age:'min age 18' }`

**Comment by fl0w** [comment] 2019-07-10 12:18
Here's how you provide a reproducible example which is almost minimal.

```js
const Koa = require('koa')
const Router = require('koa-router')
const app = new Koa()
const router = new Router()

app.use(
  router
    .post(['/resolve', '/reject'], async (ctx, next) => {
      const projects = await new Promise((resolve, reject) => {
        if (ctx.path == '/resolve') return resolve({issues:[{success:true}]})
        reject(new Error('validation failed'))
      }).catch(() => {
        ctx.throw(400, 'validation failed')
      })
      ctx.body = projects.issues[0]
    })
    .routes()
)

app.listen(3000)

```

```sh
# Promise resolves
$ curl -XPOST -v localhost:3000/resolve
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 16
< Date: Wed, 10 Jul 2019 11:57:04 GMT
< Connection: keep-alive
<
{"success":true}
```

```sh
# Promise rejects
$ curl -XPOST -v localhost:3000/reject
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< Content-Length: 17
< Date: Wed, 10 Jul 2019 11:58:59 GMT
< Connection: keep-alive
<
validation failed
```

I can't be downloading random projects to try and debug issues. That just isn't scalable nor fair. In the future, try to remove all unrelated code and boil the issue down to something more copy/paste friendly. This is also a good technique in general when trying to debug locally.

For good measure, I did mock the structure from the linked file you provided (I did not go through your project fully).

As shown above (and also proven by Koa tests) there's nothing wrong with throwing, or assigning to body. What I assume is happening is completely unrelated to Koa. `await project.save()` probably isn't even rejecting, instead just returning `undefined`, and then try to access an unknown property. This can be reproduced in REPL with:

```sh
$ node
> const projectSave = undefined
> projectSave.issues[0]
Thrown:
TypeError: Cannot read property 'issues' of undefined
```

**Comment by adrianwix** [comment] 2019-07-10 13:35
Sorry I don't have too much experience with posting on github. I tried to make the code as simple as possible
```
const Koa = require('koa')
const Router = require('koa-router');
const koaBody = require('koa-body');
const app = new Koa();
const router = new Router();
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const projectSchema = Schema({
	name: {
		type: String,
		required: true
	},
	issues: [
		{
			issue_title: {
				type: String,
				required: true
			}
		}
	]
});

const Project = mongoose.model('ProjectTest', projectSchema);

mongoose
	.connect('mongodb://username:password0@ds249127.mlab.com:49127/koaerror', { useNewUrlParser: true })
	.then(db => {
		console.log('MongoDB connected to ' + db.connection.name);

		app.use(koaBody());

		app.use(
			router
				.post('/', async (ctx, next) => {

					const { name, issue_title } = ctx.request.body;

					const project = await Project({ name, issues: [{ issue_title }] })
						.save()
						.catch(err => {
							console.log(err);
							ctx.body = { error: true, message: 'oopsie' };
						});

					// IF validation fails mongodb thorw an error obj that should be catch
					ctx.body = project.issues[0]
				})
				.get("/", ctx => {
					ctx.body = "Hola mundo"
				})
				.routes()
		);

		console.log(router.stack.map(i => i.path));

		app.listen(8000, () => {
			console.log(`> Ready on http://localhost:${8000}`);
		});

	}).catch(err => console.log(err));
```

**Comment by adrianwix** [comment] 2019-07-10 13:49
Sorry, now I tried to make the code as simple as possible.
```js
const Koa = require('koa')
const Router = require('koa-router');
const koaBody = require('koa-body');
const app = new Koa();
const router = new Router();
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const projectSchema = Schema({
	name: {
		type: String,
		required: true
	},
	issues: [
		{
			issue_title: {
				type: String,
				required: true
			}
		}
	]
});

const Project = mongoose.model('ProjectTest', projectSchema);

mongoose
	.connect('mongodb://username:password0@ds249127.mlab.com:49127/koaerror', { useNewUrlParser: true })
	.then(db => {
		console.log('MongoDB connected to ' + db.connection.name);

		app.use(koaBody());

		app.use(
			router
				.post('/', async (ctx, next) => {

					const { name, issue_title } = ctx.request.body;

					const project = await Project({ name, issues: [{ issue_title }] })
						.save()
						.catch(err => {
							console.log(err);
							ctx.body = { error: true, message: 'oopsie' };
						});

					// IF validation fails mongodb thorw an error obj that should be catch
					ctx.body = project.issues[0]
				})
				.get("/", ctx => {
					ctx.body = "Hola mundo"
				})
				.routes()
		);

		console.log(router.stack.map(i => i.path));

		app.listen(8000, () => {
			console.log(`> Ready on http://localhost:${8000}`);
		});

	});
```

A valid request would be
```
C:\Users\adrian\Code\koa-error>curl --data "name=hola&issue_title=mundo" http://localhost:8000
{"_id":"5d25e95f41210a35507ec7f1","issue_title":"mundo"}
```

Now If you don't pass the data, validation fails. MongoDB throws an error. The `.catch` is reached because it indeed calls `console.log(err)`
```
C:\Users\adrian\Code\koa-error>curl --data "" http://localhost:8000
Internal Server Error
```
and inside the server console, you get the MongoDB error
```
{
    "errors": {... },
    "_message": "Project validation failed",
   "name": "ValidationError"
}
```

```
TypeError: Cannot read property 'issues' of undefined
      at app.use.router.post (C:\Users\adrian\Code\koa-error\index.js:47:25)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by adrianwix** [comment] 2019-07-10 13:55
PD: If I do it like this I get the expected behavior. But It would be nice and sometimes useful to be able to catch the Promise using `promise.catch()`
```js
try {
	const { name, issue_title } = ctx.request.body;
	const project = await Project({ name, issues: [{ issue_title }] })
					.save();
	ctx.body = project.issues[0]
} catch (error) {
	console.log(error);
	ctx.status = 400;
        ctx.body = { error: true, message: 'oopsie' };
}
```

**Comment by fl0w** [comment] 2019-07-10 21:08
You can use `promise.catch`, as you see in my example. There's something else wrong.

**Closed by fl0w** 2019-07-10 21:08 UTC
Labels: question

**Comment by fl0w** [comment] 2019-07-10 21:10
what you're catching in your last example is the TypeError that occurs when trying to access `undefined.issues[0]`.

**Comment by adrianwix** [comment] 2019-07-10 22:17
It's rejecting the promise look at the console.log(err) that's what logs the errors that say "validation fail" because the Schema fields are marked as required. There are 2 different errors. First mongoose catch the error an return undefined. Because of that it throws the second error trying to access it as an array.
