### ISSUE TITLE
Remove Makefile, put everything in npm scripts

### ISSUE THREAD

**Issue by felixfbecker** [koajs/koa#559] opened 2015-10-27 19:17 UTC
`make` is not available on Windows. NPM scripts however can run anywhere. Makefiles are also unnecessarily complicated for something simple as running `mocha` or `eslint` with a few options. Also, in npm scripts, you don't have to specify the path of the binary.
@stojanovic looking forward to your PR

**Comment by targos** [comment] 2015-10-27 19:27
I'm working on it ;)

**Comment by stojanovic** [comment] 2015-10-27 19:34
Me too :)
Go for it, since I just stared :)

**Comment by targos** [comment] 2015-10-27 19:42
https://github.com/koajs/koa/pull/560

**Comment by felixfbecker** [comment] 2015-10-27 20:12
I don't get why `make` is faster... Aren't they both just ways of calling js modules? Just that for the one method, I need `build-essential` on my machine.
Btw as far as I know in Windows you set env variables with `set`

**Comment by jonathanong** [comment] 2016-03-04 03:47
how many of koajs committers/contributors use windows?

**Comment by PlasmaPower** [comment] 2016-03-04 03:56
Also, remember that cygwin/mingw, while somewhat of a pain, are still options, so it's not totally unworkable for Windows users.

**Comment by jonathanong** [comment] 2016-05-14 15:40
who's for and against this? my personal opinion: we should use npm scripts for wider compat, but not at the expense of having an unmanageable `package.scripts` object.

**Comment by alsotang** [comment] 2016-05-14 21:06
I support Makefile because npm script is a fool choose for project. It only
support raw string, only.

2016-05-14 23:40 GMT+08:00 jongleberry <notifications@github.com>:

**Comment by fl0w** [comment] 2016-05-14 21:58
I'm with jonathan, npm scripts unless they become unbearable.

**Comment by detailyang** [comment] 2016-05-24 16:06
Makefile is enough and  npm scripts is not bad. But for universality, maybe npm scripts is more better:)

**Comment by jeffijoe** [comment] 2016-06-24 11:43
I vote npm scripts as well - they can get hairy, sure, but thats when you start breaking them out and chaining them instead.

**Comment by PlasmaPower** [comment] 2016-06-24 11:45
@jeffijoe Have a good way to do `mocha test/**/*.js` that's compatible

**Comment by zanaca** [comment] 2017-02-05 07:33
I have compared a machine running Node that was started with NPM  and  one that was started in pure node command. The one started by ```npm start``` was using more memory and cpu just because NPM was "processing"  the Node process itself. Since that day my Makefile calls node directly.

So, maybe, Makefile should be preserved and you guys should run a benchmark.

**Comment by tj** [comment] 2017-02-05 16:20
That's one reason I don't use npm scripts, the extra ~300ms bugs me, and it adds extra output. Not a huge deal, but if Windows was less of a mess it wouldn't be a big deal :D

**Comment by jeffijoe** [comment] 2017-02-05 16:25
@tj having just switched to Mac from Windows myself and I can confirm the mess that is Windows 😄

**Comment by dominhhai** [comment] 2017-02-05 23:53
Do NOT replace Makefile by NPM scripts, the slow NPM scripts is not really good. How about adding scripts for Windows users?

**Comment by EduardoRFS** [comment] 2017-02-06 01:11
Yarn apparently solve npm scripts delay.

**Comment by zanaca** [comment] 2017-02-06 01:25
```npm start``` take some extra RAM and CPU cycles.  Start your application, with load, and than run ```top``` in shell  to see how many memory and CPU are being used.

**Comment by PlasmaPower** [comment] 2017-02-06 01:30
With this simple of a task, we could also consider just writing a Node.JS script, then adding barebone .sh and .cmd wrappers around it.

**Comment by dead-horse** [comment] 2017-05-11 03:40
closed via #981

**Closed by dead-horse** 2017-05-11 03:40 UTC
Labels: question
