### ISSUE TITLE
the lastest version numbers have gone back in time

### ISSUE THREAD

**Issue by 75lb** [koajs/koa#839] opened 2016-10-21 19:30 UTC
technically, the latest version (v2.0.0-alpha.7) is a lower version than v2.0.0 from March.. in npm v3.10, this command installs v2.0.0:

```
$ npm i koa@^2.0.0-alpha
```

Only a mild annoyance, but `"koa": "^2.0.0-alpha"` in my package.json doesn't install the latest release as desired.

**Comment by jonathanong** [comment] 2016-10-21 22:46
try `npm i koa@next`. if that doesn't work, we'll have to fix these damn npm tags

**Comment by 75lb** [comment] 2016-10-21 22:52
`npm i koa@next --save` works fine thanks but it's open-ended.. (i don't want to depend on a tag which might later point to something incompatible, breaking my app)

**Comment by jonathanong** [comment] 2016-10-28 06:41
i would say it's better because we're not using strict-semver versions, so depending on the alpha tag will never give you the latest updates. however, i don't think v3 will be marked as `next` for very long, so i think the `next` tag will die at v2, keeping you safe.

**Comment by AubreyHewes** [comment] 2016-11-05 00:01
The issue is valid, and actually has nothing to do with `npm`, it's down to this project's release management; the release/tag management of the project in github.

The project has a release `2.0.0` which is older than the latest `2.0.0-alpha.X` releases. 

This availability of release `2.0.0` supersedes `2.0.0-alpha.X` releases, this is basic semver. 
Therefore anyone trying to install using semver `2.0.0-alpha.X` will get the outdated `2.0.0` release and not the latest `2.0.0-alpha.X` release.

The project should remove release `2.0.0` as it is not `2.0.0` due to `2.0.0-alpha.X` tags still being released... see the [release history](https://github.com/koajs/koa/releases).  

Sidenotes; 

@75lb using `^2.0.0-alpha` will install anything up to `3.0.0` -- basic semver.. your app could break at any time ;-)

@jonathanong using `next` is a bit like using `master`, just _slightly_ more controlled ;-)

**Comment by jonathanong** [comment] 2017-02-25 06:20
https://github.com/koajs/koa/issues/812

**Closed by jonathanong** 2017-02-25 06:20 UTC
